export const data = [
    {
        id: "1",
        name: "Acapulco Gold",
        thc: "13.70%",
        cbd: "0.12%",
        cbg: "0.15%",
        rating: 4.5,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Sativa",
        climate: "Humid",
        difficulty: "Medium",
        fungalResistance: "High",
        indoorYieldInGramsMax: 500,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Ánimo, Euforia, Creatividad",
        negatives: "Ojos Secos, Boca Seca, Paranoia, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Acapulco-gold.jpg",
        stock: 100,
        imgAttributionLink:
            "https://commons.wikimedia.org/w/index.php?curid=8998618",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "2",
        name: "ACDC",
        thc: "1.40%",
        cbd: "11.20%",
        cbg: "0.20%",
        rating: 4.5,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Difficult",
        fungalResistance: "Medium",
        indoorYieldInGramsMax: 340,
        outdoorYieldInGramsMax: 453,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Euforia, Sueño, Relajación",
        negatives: "Boca Seca, Mareo, Ojos secos, Letargo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/ACDC.png",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "3",
        name: "Afgoo",
        thc: "17.04%",
        cbd: "0.06%",
        cbg: "0.07%",
        rating: 4,
        helps: "Estrés, Insomnio, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: "Low",
        indoorYieldInGramsMax: 400,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 20.0,
        heightInInchesMax: 30.0,
        feelings: "Relajación, Alegría, Euforia",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Afgoo.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "4",
        name: "AK-47",
        thc: "16.60%",
        cbd: "0.30%",
        cbg: "0.50%",
        rating: 4.1,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: "Medium",
        indoorYieldInGramsMax: 39,
        outdoorYieldInGramsMax: 396,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Energética, Relajación, Estimulante, Creatividad, Alegría",
        negatives: "Boca Seca, Mareo, Ojos secos, Paranoia, Letargo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/AK47-WeedStrain.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "5",
        name: "Alaskan Thunder Fuck",
        thc: "15.60%",
        cbd: "0.15%",
        cbg: "0.50%",
        rating: 4.3,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: "Medium",
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 900,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Euforia, Elevado",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Alaskan_thunder_fuck.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "6",
        name: "Amnesia",
        thc: "18.20%",
        cbd: "2.00%",
        cbg: "0.30%",
        rating: 4.2,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 120,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Euforia, Creatividad, Elevado, Relajación",
        negatives: "Ojos secos, Boca Seca, Mareo, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Amnesia.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "7",
        name: "Banana OG",
        thc: "21.36%",
        cbd: "0.14%",
        cbg: "0.54%",
        rating: 4.3,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Indica",
        climate: "Humid",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 35,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Alegría, Relajación, Euforia",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Banana-OG.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "8",
        name: "Berry White",
        thc: "17.30%",
        cbd: "0.04%",
        cbg: "2.00%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Alegría, Elevado, Euforia",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/BerryWhite.jpg",
        stock: 100,
        imgAttributionLink: "https://herb.co/strains/berry-white/",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "9",
        name: "Blue Cookies",
        thc: "21%",
        cbd: "0.05%",
        cbg: "1.13%",
        rating: 4.7,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Indica",
        climate: "All Seasons",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 460,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Alegría, Elevado, Euforia",
        negatives: "Boca Seca, Ojos secos, Sueño",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Blue-Cookies.jpg",
        stock: 100,
        imgAttributionLink:
            "https://herb.co/strains/blue-cookies-marijuana-strain/",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "10",
        name: "Blue Dream",
        thc: "19.20%",
        cbd: "0.10%",
        cbg: "0.40%",
        rating: 4.3,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Sativa",
        climate: "All Seasons",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 500,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 90.0,
        heightInInchesMax: null,
        feelings: "Relajación, Creatividad, Energética, Estimulante",
        negatives: "Boca Seca, Ojos secos, Mareo, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/BlueDream.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "11",
        name: "Bruce Banner",
        thc: "18.80%",
        cbd: "1.20%",
        cbg: "0.90%",
        rating: 4.5,
        helps: "Estrés, Depresión, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 900,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 14.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Euforia, Alegría, Relajación",
        negatives: "Mareo, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Bruce-banner.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "12",
        name: "Bubba Kush",
        thc: "18.60%",
        cbd: "0.10%",
        cbg: "0.60%",
        rating: 4.3,
        helps: "Estrés, Dolor, Insomnio",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 400,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 20.0,
        heightInInchesMax: 30.0,
        feelings: "Relajación, Sueño, Euforia, Alegría",
        negatives: "Boca Seca, Mareo, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Bubba_kush.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "13",
        name: "Candyland",
        thc: "18.40%",
        cbd: "0.08%",
        cbg: "0.80%",
        rating: 4.5,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 90,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Elevado, Relajación",
        negatives: "Sed, Ansiedad, Mareo, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/candyland-strain.jpg",
        stock: 100,
        imgAttributionLink: "https://www.leafly.com/strains/candyland",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "14",
        name: "Canna-Tsu",
        thc: "2.00%",
        cbd: "7.10%",
        cbg: "0.28%",
        rating: 4.6,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 300,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Euforia, Sueño, Alegría",
        negatives: "Mareo, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Canna-Tsu.jpg",
        stock: 100,
        imgAttributionLink: "https://herb.co/strains/canna-tsu/",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "15",
        name: "Cannatonic",
        thc: "2.40%",
        cbd: "10.10%",
        cbg: "0.70%",
        rating: 4.3,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Híbrida",
        climate: "All Seasons",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Sueño, Euforia",
        negatives: "Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Cannatonic.jpg",
        stock: 100,
        imgAttributionLink: "https://www.leafly.com/strains/cannatonic",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "16",
        name: "Chernobyl",
        thc: "16.40%",
        cbd: "0.11%",
        cbg: "0.38%",
        rating: 4.3,
        helps: "Estrés, Depresión, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Euforia, Relajación",
        negatives: "Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Chernobyl.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "17",
        name: "Cinderella 99",
        thc: "15.70%",
        cbd: "0.20%",
        cbg: "0.60%",
        rating: 4.2,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Híbrida",
        climate: "All Seasons",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 60,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Alegría, Energética, Euforia",
        negatives: "Ansiedad, Paranoia, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Cinderella99.jpg",
        stock: 100,
        imgAttributionLink:
            "https://www.seeds66.com/cinderella-99-from-seeds66_4",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "18",
        name: "Clementine",
        thc: "18%",
        cbd: "0.18%",
        cbg: "0.88%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Sativa",
        climate: "Humid",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 425,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Energética, Euforia",
        negatives: "Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Clementine.jpg",
        stock: 100,
        imgAttributionLink: "https://tokeandsmokeshop.io/product/clementine/",
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "19",
        name: "Cookies and Cream",
        thc: "23.50%",
        cbd: "0.20%",
        cbg: "1.30%",
        rating: 4.5,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Difficult",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 460,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Relajación, Euforia",
        negatives: "Mareo, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Cookies-n-cream.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "20",
        name: "Cracker Jack",
        thc: "19.80%",
        cbd: "0.10%",
        cbg: "1.00%",
        rating: 4,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Energética, Enfoque, Creatividad",
        negatives: "Paranoia, Ansiedad, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Cracker_Jack.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "21",
        name: "Critical Mass",
        thc: "10.40%",
        cbd: "5.70%",
        cbg: "0.81%",
        rating: 4.2,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 70,
        outdoorYieldInGramsMax: 800,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Alegría, Sueño",
        negatives: "Mareo, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Critical_Mass.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "22",
        name: "Death Star",
        thc: "16.81%",
        cbd: "0.11%",
        cbg: "0.71%",
        rating: 4.5,
        helps: "Estrés, Dolor, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 340,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Relajación, Alegría, Sueño, Euforia",
        negatives: "Mareo, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Death_Star.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "23",
        name: "Do Si Dos",
        thc: "20.7%",
        cbd: "0.07%",
        cbg: "1.00%",
        rating: 4.6,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "Humid",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 700,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Elevado, Relajación, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Do_Si_Dos.jpg",
        stock: 100,
        imgAttributionLink:
            "https://www.spokesman.com/stories/2020/jun/12/strain-month-do-si-dos/",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "24",
        name: "Durban Poison",
        thc: "17.80%",
        cbd: "0.60%",
        cbg: "0.80%",
        rating: 4.4,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Energética, Alegría, Elevado, Enfoque",
        negatives: "Ansiedad, Paranoia, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Durban_Poison.jpg",
        stock: 100,
        imgAttributionLink:
            "https://www.hytiva.com/strains/sativa/durban-poison",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "25",
        name: "Dutch Treat",
        thc: "22.37%",
        cbd: "0.20%",
        cbg: "0.95%",
        rating: 4.3,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: null,
        outdoorYieldInGramsMax: null,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Euforia, Elevado, Creatividad",
        negatives: "Mareo, Boca Seca, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Dutch_Treat.jpg",
        stock: 100,
        imgAttributionLink: "https://www.leafly.com/strains/dutch-treat",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "26",
        name: "Forbidden Fruit",
        thc: "15.30%",
        cbd: "0.03%",
        cbg: "0.30%",
        rating: 4.6,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 425,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Euforia, Relajación, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Forbidden_Fruit.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "27",
        name: "Fruity Pebbles OG",
        thc: "19%",
        cbd: "0.20%",
        cbg: "0.80%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Moderate",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Relajación, Euforia, Risueño, Elevado",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Fruity_Pebbles.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "28",
        name: "G-13",
        thc: "16.20%",
        cbd: "0.10%",
        cbg: "0.40%",
        rating: 4.3,
        helps: "Estrés, Dolor, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 54,
        outdoorYieldInGramsMax: 1100,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Relajación, Euforia, Sueño",
        negatives: "Paranoia, Mareo, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/G-13.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "29",
        name: "Gelato",
        thc: "18.70%",
        cbd: null,
        cbg: "0.70%",
        rating: 4.6,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Humid",
        difficulty: "Difficult",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 425,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 0.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Alegría, Relajación, Euforia, Estimulante",
        negatives: "Boca Seca, Ojos secos, Mareo, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Gelato_.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "30",
        name: "Girl Scout Cookies",
        thc: "19.10%",
        cbd: "0.27%",
        cbg: "0.98%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 280,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Relajación, Euforia, Hambre, Risueño",
        negatives: "Boca Seca, Ojos secos, Mareo, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Girl_Scout_Cookies.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "31",
        name: "GMO",
        thc: "25.7%",
        cbd: "0.15%",
        cbg: "1.05%",
        rating: 4.7,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Relajación, Euforia",
        negatives: "Boca Seca, Ojos secos, Mareo",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/GMO.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "32",
        name: "Golden Goat",
        thc: "18.00%",
        cbd: "0.11%",
        cbg: "0.75%",
        rating: 4.5,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 425,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Elevado, Euforia, Verborragia",
        negatives: "Boca seca, Ojos secos, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Golden_Goat.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "33",
        name: "Gorilla Glue",
        thc: "21.30%",
        cbd: "0.11%",
        cbg: "0.50%",
        rating: 4.6,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Relajación, Euforia",
        negatives: "Mareo, Boca Seca, Ojos secos, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Gorilla_Glue.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "34",
        name: "Granddaddy Purple",
        thc: "20%",
        cbd: "0.10%",
        cbg: "0.60%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Indica",
        climate: "Humid",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 300,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 20.0,
        heightInInchesMax: 30.0,
        feelings: "Relajación, Sueño, Euforia, Alegría, Hambre",
        negatives: "Mareo, Boca Seca, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Granddaddy_Purple.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "35",
        name: "Grease Monkey",
        thc: "20.3%",
        cbd: "0.08%",
        cbg: "0.76%",
        rating: 4.6,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Sueño, Relajación, Alegría, Hambre",
        negatives: "Mareo, Boca Seca, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Grease_Monkey.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "36",
        name: "Harle-Tsu",
        thc: "0.60%",
        cbd: "11%",
        cbg: null,
        rating: 4.5,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 30,
        outdoorYieldInGramsMax: 460,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Sueño, Enfoque, Despierto",
        negatives: "Mareo, Boca Seca, Dolor de cabeza, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Harle-Tsu.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "37",
        name: "Harlequin",
        thc: "9%",
        cbd: "6.40%",
        cbg: "0.40%",
        rating: 4.3,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Sativa",
        climate: "All Seasons",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 70,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Sueño, Euforia, Enfoque, Elevado",
        negatives: "Ansiedad, Mareo, Dolor de Cabeza, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Harlequin.jpg",
        stock: 100,
        imgAttributionLink: "https://www.leafly.com/strains/harlequin",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "38",
        name: "Headband",
        thc: "20.80%",
        cbd: "0.08%",
        cbg: "0.50%",
        rating: 4.2,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Euforia, Relajación, Elevado, Creatividad",
        negatives: "Mareo, Boca Seca, Dolor de cabeza, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Headband.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "39",
        name: "Hindu Kush",
        thc: "17.10%",
        cbd: null,
        cbg: "0.50%",
        rating: 4.3,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 35,
        outdoorYieldInGramsMax: 450,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Sueño, Euforia, Alegría, Hambre",
        negatives: "Paranoia, Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Hindu_Kush.jpg",
        stock: 100,
        imgAttributionLink: "https://growdiaries.com/seedbank/msnl/hindu-kush",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "40",
        name: "Jack Herer",
        thc: "18%",
        cbd: "0.10%",
        cbg: "1%",
        rating: 4.4,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Creatividad, Energética, Elevado",
        negatives: "Ansiedad, Boca Seca, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Jack_Herer.jpg",
        stock: 100,
        imgAttributionLink:
            "https://cannabispharmuk.com/product/jack-herer-cannabis-strain-uk/",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "41",
        name: "Jack the Ripper",
        thc: "19.34%",
        cbd: "0.17%",
        cbg: "0.56%",
        rating: 4.2,
        helps: "Estrés, Ansiedad, Dolor",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 28,
        outdoorYieldInGramsMax: 340,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 60.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Energética, Euforia, Creatividad",
        negatives: "Paranoia, Mareo, Boca Seca, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Jack_the_Ripper.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "42",
        name: "Jet Fuel",
        thc: "21.36%",
        cbd: "0.11%",
        cbg: "0.53%",
        rating: 4.5,
        helps: "Estrés, Depresión, Ansiedad",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 35,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Euforia, Elevado, Enfoque",
        negatives: "Paranoia, Mareo, Boca Seca, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Jet_Fuel.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "43",
        name: "Kosher Kush",
        thc: "18.47%",
        cbd: "0.13%",
        cbg: "0.71%",
        rating: 4.5,
        helps: "Dolor, Estrés, Insomnio",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 450,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Alegría, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Kosher_Kush.jpg",
        stock: 100,
        imgAttributionLink:
            "https://growdiaries.com/seedbank/garden-of-green/kosher-kush",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "44",
        name: "LA Confidential",
        thc: "17.10%",
        cbd: "0.09%",
        cbg: "0.30%",
        rating: 4.3,
        helps: "Dolor, Estrés, Ansiedad",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 45,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Alegría, Elevado, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/LA_Confidential.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "45",
        name: "Lemon Tree",
        thc: "17%",
        cbd: "0.03%",
        cbg: "0.53%",
        rating: 4.5,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "All Seasons",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 42,
        outdoorYieldInGramsMax: 480,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Alegría, Elevado, Energética",
        negatives: "Mareo, Ansiedad, Dolor de Cabeza",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Lemon_Tree.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "46",
        name: "Northern Lights",
        thc: "22%",
        cbd: "0.1%",
        cbg: "1%",
        rating: 4.4,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 42,
        outdoorYieldInGramsMax: 56,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Creatividad, Energética, Relajación, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Northern_Lights.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "47",
        name: "OG Kush",
        thc: "19.11%",
        cbd: "0.10%",
        cbg: "0.58%",
        rating: 4.3,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Difficult",
        fungalResistance: null,
        indoorYieldInGramsMax: 34,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Relajación, Euforia, Hambre, Sueño",
        negatives: "Paranoia, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/OG_Kush.jpg",
        stock: 100,
        imgAttributionLink:
            "https://weedmaps.com/brands/the-good/products/the-good-og-kush/reviews",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: 48,
        name: "Pennywise",
        thc: "9.40%",
        cbd: "9.30%",
        cbg: "0.30%",
        rating: 4.5,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "All Seasons",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 70,
        outdoorYieldInGramsMax: 250,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Relajación, Enfoque, Euforia, Sueño",
        negatives: "Ansiedad, Mareo, Boca Seca",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Pennywise.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "49",
        name: "Platinum OG",
        thc: "18.60%",
        cbd: "0.70%",
        cbg: "0.70%",
        rating: 4.4,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 34,
        outdoorYieldInGramsMax: 340,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Relajación, Alegría, Sueño, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Platinum_OG.jpg",
        stock: 100,
        imgAttributionLink:
            "https://essencevegas.com/kb/cannabis-strains/mmg-platinum-og/",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "50",
        name: "Purple Kush",
        thc: "20.8%",
        cbd: "0.1%",
        cbg: "0.3%",
        rating: 4.2,
        helps: "Estrés, Dolor, Insomnio",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 260,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 20.0,
        heightInInchesMax: 30.0,
        feelings: "Relajación, Alegría, Sueño, Hambre",
        negatives: "Boca Seca, Paranoia, Mareo, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Purple_Kush.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "51",
        name: "Purple Urkle",
        thc: "20.60%",
        cbd: "0.10%",
        cbg: "0.20%",
        rating: 4.3,
        helps: "Estrés, Dolor, Insomnio",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 255,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Euforia, Elevado, Sueño, Hambre",
        negatives: "Boca Seca, Mareo, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Purple_Urkle.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "52",
        name: "Ringo’s Gift",
        thc: "0.60%",
        cbd: "14.70%",
        cbg: "0.60%",
        rating: 4.6,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Sativa",
        climate: "All Seasons",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 28,
        outdoorYieldInGramsMax: 370,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Sueño, Enfoque, Elevado",
        negatives: "Mareo, Boca Seca, Dolor de cabeza, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Ringos_Gift.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "53",
        name: "Sensi Star",
        thc: "20.6%",
        cbd: null,
        cbg: "0.9%",
        rating: 4.1,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 28,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Euforia, Elevado, Sueño, Hambre, Hormigueo",
        negatives: "Boca Seca, Mareo, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Sensi_Star.jpg",
        stock: 100,
        imgAttributionLink:
            "https://cannacabana.com/products/7acres-sensi-star",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "54",
        name: "SFV OG",
        thc: "17.30%",
        cbd: "0.10%",
        cbg: "0.70%",
        rating: 4.4,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 34,
        outdoorYieldInGramsMax: 370,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Alegría, Relajación, Euforia, Sueño",
        negatives: "Ansiedad, Boca Seca, Paranoia, Dolor de Cabeza",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/SFV_OG.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "55",
        name: "Skywalker OG",
        thc: "20.40%",
        cbd: "0.07%",
        cbg: "0.85%",
        rating: 4.5,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 800,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Sueño, Hormigueo",
        negatives: "Mareo, Boca Seca, Ojos secos, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Skywalker_OG.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "56",
        name: "Snoop's Dream",
        thc: "23.17%",
        cbd: "0.22%",
        cbg: "0.34%",
        rating: 4.5,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 35,
        outdoorYieldInGramsMax: 280,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Alegría, Elevado, Euforia",
        negatives: "Paranoia, Ansiedad, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Snoops_Dream.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "57",
        name: "Sour Diesel",
        thc: "19%",
        cbd: "0.10%",
        cbg: "0.40%",
        rating: 4.3,
        helps: "Estrés, Ansiedad, Depresión",
        strainType: "Sativa",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 700,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Elevado, Energética, Verborragia, Creatividad",
        negatives: "Mareo, Paranoia, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Sour_Diesel.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "58",
        name: "Sour Tsunami",
        thc: "1.00%",
        cbd: "11.20%",
        cbg: "0.40%",
        rating: 4.4,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Indica",
        climate: "All Seasons",
        difficulty: "Difficult",
        fungalResistance: null,
        indoorYieldInGramsMax: 42,
        outdoorYieldInGramsMax: 450,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Sueño, Alegría, Hormigueo, Enfoque",
        negatives: "Mareo, Boca Seca, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Sour_Tsunami.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "59",
        name: "Stephen Hawking Kush",
        thc: "2.10%",
        cbd: "13.10%",
        cbg: "0.30%",
        rating: 4.7,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "All Seasons",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Sueño, Relajación, Euforia, Enfoque",
        negatives: "Mareo, Boca Seca, Dolor de cabeza, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Stephen_Hawking_Kush.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "60",
        name: "Strawberry Banana",
        thc: "21.54%",
        cbd: "0.06%",
        cbg: "0.87%",
        rating: 4.5,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Indica",
        climate: "Humid",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 650,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Relajación, Alegría, Elevado, Hambre",
        negatives: "Mareo, Boca Seca, Ansiedad, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Strawberry_Banana.jpg",
        stock: 100,
        imgAttributionLink: "https://thcdesign.com/strains/strawberry-banana/",
        imgCreativeCommons: true,
        idCategory: "cepas",
    },
    {
        id: "61",
        name: "Strawberry Cough",
        thc: "16.50%",
        cbd: "0.07%",
        cbg: "0.50%",
        rating: 4.3,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Sativa",
        climate: "Humid",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 40,
        outdoorYieldInGramsMax: 400,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 60.0,
        heightInInchesMax: 70.0,
        feelings: "Elevado, Euforia, Creatividad, Verborragia, Energética",
        negatives: "Boca Seca, Mareo, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Strawberry_Cough.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "62",
        name: "Sunset Sherbet",
        thc: "17.00%",
        cbd: "0.08%",
        cbg: "0.64%",
        rating: 4.6,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 28,
        outdoorYieldInGramsMax: 311,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Sueño, Alegría, Elevado, Risueño, Relajación",
        negatives: "Ansiedad, Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Sunset_Sherbet.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "63",
        name: "Super Lemon Haze",
        thc: "18.60%",
        cbd: "0.09%",
        cbg: "1.20%",
        rating: 4.4,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 70,
        outdoorYieldInGramsMax: 1100,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Elevado, Energética, Creatividad",
        negatives: "Mareo, Boca Seca, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Super_Lemon_Haze.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "64",
        name: "Superglue",
        thc: "20.10%",
        cbd: "0.04%",
        cbg: "0.40%",
        rating: 4.6,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Indica",
        climate: "Humid",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 650,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 20.0,
        heightInInchesMax: 30.0,
        feelings: "Relajación, Alegría, Euforia, Hambre",
        negatives: "Mareo, Boca Seca, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Superglue.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "65",
        name: "Tangie",
        thc: "13.70%",
        cbd: "0.05%",
        cbg: "0.50%",
        rating: 4.4,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 50,
        outdoorYieldInGramsMax: 500,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Alegría, Elevado, Energética, Verborragia",
        negatives: "Boca Seca, Mareo, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Tangie.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "66",
        name: "Trainwreck",
        thc: "16.14%",
        cbd: "0.08%",
        cbg: "1%",
        rating: 4.2,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 45,
        outdoorYieldInGramsMax: 700,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Elevado, Relajación, Alegría, Creatividad, Euforia",
        negatives: "Boca Seca, Mareo, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Trainwreck.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "67",
        name: "Wedding Cake",
        thc: "15.7%",
        cbd: "0.36%",
        cbg: "0.60%",
        rating: 4.6,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Humid",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 51,
        outdoorYieldInGramsMax: 510,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 30.0,
        heightInInchesMax: 50.0,
        feelings: "Relajación, Alegría, Elevado, Estimulante, Hambre",
        negatives: "Ansiedad, Mareo, Boca Seca, Paranoia",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Wedding_Cake.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "68",
        name: "White Fire",
        thc: "19%",
        cbd: "0.13%",
        cbg: "0.56%",
        rating: 4.5,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 550,
        floweringWeeksMin: 10.0,
        floweringWeeksMax: 12.0,
        heightInInchesMin: 50.0,
        heightInInchesMax: 70.0,
        feelings: "Alegría, Relajación, Euforia, Elevado, Creatividad",
        negatives: "Boca Seca, Ansiedad, Mareo, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/White_Fire.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "69",
        name: "XJ13",
        thc: "18.25%",
        cbd: "0.06%",
        cbg: "0.93%",
        rating: 4.3,
        helps: "Ansiedad, Depresión, Estrés",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Medium",
        fungalResistance: null,
        indoorYieldInGramsMax: 60,
        outdoorYieldInGramsMax: 600,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 70.0,
        heightInInchesMax: 90.0,
        feelings: "Elevado, Alegría, Energética, Creatividad, Verborragia",
        negatives: "Boca Seca, Ansiedad, Paranoia, Ojos secos",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/XJ13.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "70",
        name: "Zkittlez",
        thc: "14.18%",
        cbd: "0.04%",
        cbg: "0.54%",
        rating: 4.6,
        helps: "Ansiedad, Estrés, Dolor",
        strainType: "Híbrida",
        climate: "Dry",
        difficulty: "Easy",
        fungalResistance: null,
        indoorYieldInGramsMax: 35,
        outdoorYieldInGramsMax: 480,
        floweringWeeksMin: 7.0,
        floweringWeeksMax: 9.0,
        heightInInchesMin: 60.0,
        heightInInchesMax: 70.0,
        feelings: "Relajación, Alegría, Sueño, Hambre",
        negatives: "Boca Seca, Mareo, Ansiedad",
        price: 1,
        imgThumb:
            "https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Zkittlez.jpg",
        stock: 100,
        imgAttributionLink: null,
        imgCreativeCommons: false,
        idCategory: "cepas",
    },
    {
        id: "71",
        name: "Chemdawg",
        thc: "18%",
        cbd: "0%",
        cbg: "1%",
        rating: 4.3,
        feelings: "Euforia, Inspiración, Creatividad",
        negatives: "Boca seca, Ojos secos, Mareo",
        helps: "Estrés, Ansiedad, Dolor",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-1.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Híbrida",
        idCategory: "cepas",
    },
    {
        id: "72",
        name: "Skunk Dawg",
        thc: "21%",
        cbd: "0%",
        cbg: "1%",
        rating: 4.5,
        feelings: "Verborragia, Enfoque, Energética",
        negatives: "Boca seca, Paranoia, Ansiedad",
        helps: "Estrés, Depresión, Ansiedad",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-32.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Sativa",
        idCategory: "cepas",
    },
    {
        id: "73",
        name: "Blueberry AK",
        thc: "20%",
        cbd: "0%",
        cbg: "1%",
        rating: 4.7,
        feelings: "Euforia, Relajación, Hambre",
        negatives: "Dolor de cabeza, Mareo, Boca seca",
        helps: "Estrés, Ansiedad, Depresión",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-16.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Híbrida",
        idCategory: "cepas",
    },
    {
        id: "74",
        name: "Strawberry Cheesecake",
        thc: "16%",
        cbd: "0%",
        cbg: "0%",
        rating: 4.5,
        feelings: "Alegría, Sueño, Euforia",
        negatives: "Ojos secos, Mareo, Boca seca",
        helps: "Dolor, Estrés, Depresión",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-27.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Indica",
        idCategory: "cepas",
    },
    {
        id: "75",
        name: "Cereal Milk",
        thc: "22%",
        cbd: "0%",
        cbg: "1%",
        rating: 4.6,
        feelings: "Relajacion, Risueño, Despierto",
        negatives: "Dolor de cabeza, Ansiedad, Paranoia",
        helps: "Ansiedad, Depresión, Estrés",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/short-dense-heavy/strain-4.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Híbrida",
        idCategory: "cepas",
    },
    {
        id: "76",
        name: "Cherry Cheesecake",
        thc: "0%",
        cbd: "11%",
        cbg: "0%",
        rating: 5.0,
        feelings: "Risueño, Verborragia, Enfoque",
        negatives: "Boca seca",
        helps: "Ansiedad, Enfermedad de Crohn's",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-19.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Indica",
        idCategory: "cepas",
    },
    {
        id: "77",
        name: "Cherry On Top",
        thc: "0%",
        cbd: "8%",
        cbg: "0%",
        rating: 4.5,
        feelings: "Alegría, Sueño, Hambre",
        negatives: "Boca seca",
        helps: "Depresión, Ansiedad, Insomnio",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/generic/strain-18.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Híbrida",
        idCategory: "cepas",
    },
    {
        id: "78",
        name: "Mochi",
        thc: "10%",
        cbd: "0%",
        cbg: "0%",
        rating: 4.6,
        feelings: "Sueño, Relajación, Hambre",
        negatives: "Ansiedad, Paranoia, Ojos secos",
        helps: "Ansiedad, Insomnio, Estrés",
        price: 1,
        imgThumb:
            "https://images.leafly.com/flower-images/defaults/purple/strain-5.png?auto=compress%2Cformat&w=350&dpr=1",
        stock: 100,
        strainType: "Híbrida",
        idCategory: "cepas",
    },
    {
        id: "79",
        name: "Sedas",
        price: 500,
        imgThumb: "/sedas.jpg",
        stock: 50,
        idCategory: "shop",
    },
    {
        id: "80",
        name: "Encendedor",
        price: 800,
        imgThumb: "/encendedor.jpg",
        stock: 50,
        idCategory: "shop",
    },
    {
        id: "81",
        name: "Vaporizador Vulcan",
        price: 10500,
        imgThumb: "/vaporizador.jpg",
        stock: 50,
        idCategory: "vaporizadores",
    },
    {
        id: "82",
        name: "Pikachu",
        price: 5500,
        imgThumb: "/pikachu.jpg",
        stock: 50,
        idCategory: "shop",
    },
];

export const getProductos = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(data);
        }, 100);
    });
};

// funcion similar pero que retorne 1 solo item

export const getUnProducto = (id) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            const producto = data.find((prod) => prod.id === id);
            resolve(producto);
        }, 100);
    });
};

// Funcion que retorna una categoria.

export const getProductosPorCategoria = (idCategory) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            const ProductosCategoria = data.filter(
                (prod) => prod.idCategory === idCategory
            );
            resolve(ProductosCategoria);
        }, 100);
    });
};
